
package mypackage;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PriceDatabase", targetNamespace = "http://impl.webservice.finalproject/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PriceDatabase {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "http://impl.webservice.finalproject/", className = "mypackage.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://impl.webservice.finalproject/", className = "mypackage.UpdateResponse")
    @Action(input = "http://impl.webservice.finalproject/PriceDatabase/updateRequest", output = "http://impl.webservice.finalproject/PriceDatabase/updateResponse")
    public void update(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    double arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://impl.webservice.finalproject/", className = "mypackage.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://impl.webservice.finalproject/", className = "mypackage.DeleteResponse")
    @Action(input = "http://impl.webservice.finalproject/PriceDatabase/deleteRequest", output = "http://impl.webservice.finalproject/PriceDatabase/deleteResponse")
    public void delete(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "create", targetNamespace = "http://impl.webservice.finalproject/", className = "mypackage.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://impl.webservice.finalproject/", className = "mypackage.CreateResponse")
    @Action(input = "http://impl.webservice.finalproject/PriceDatabase/createRequest", output = "http://impl.webservice.finalproject/PriceDatabase/createResponse")
    public void create(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    double arg1);

    /**
     * 
     * @return
     *     returns java.util.List<mypackage.PriceDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPrices", targetNamespace = "http://impl.webservice.finalproject/", className = "mypackage.GetAllPrices")
    @ResponseWrapper(localName = "getAllPricesResponse", targetNamespace = "http://impl.webservice.finalproject/", className = "mypackage.GetAllPricesResponse")
    @Action(input = "http://impl.webservice.finalproject/PriceDatabase/getAllPricesRequest", output = "http://impl.webservice.finalproject/PriceDatabase/getAllPricesResponse")
    public List<PriceDto> getAllPrices();

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCostById", targetNamespace = "http://impl.webservice.finalproject/", className = "mypackage.GetCostById")
    @ResponseWrapper(localName = "getCostByIdResponse", targetNamespace = "http://impl.webservice.finalproject/", className = "mypackage.GetCostByIdResponse")
    @Action(input = "http://impl.webservice.finalproject/PriceDatabase/getCostByIdRequest", output = "http://impl.webservice.finalproject/PriceDatabase/getCostByIdResponse")
    public double getCostById(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0);

}
